name: Run 2S Monitor Bot

on:
  schedule:
    # Memulai ulang bot secara otomatis setiap 5 jam untuk menghindari limit otomatis 6 jam dari GitHub
    - cron: '0 */5 * * *'
  workflow_dispatch: # Mengizinkan Anda menyalakan bot secara manual dari tab Actions di GitHub

concurrency:
  group: bot-runner
  cancel-in-progress: true # Akan mematikan proses bot yang lama jika jadwal baru (cron) dimulai, mencegah penumpukan proses

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Run Script
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python 2s-monitoring-recap.py
